name: SAST - SonarCloud
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request_target:
  workflow_dispatch:

permissions: {}

jobs:
  sast:
    permissions:
      contents: read
    uses: eu-digital-identity-wallet/eudi-infra-ci/.github/workflows/sast_action_libs_kotlin.yml@feat/sast_kotlin_libs
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
